CREATE TABLE IF NOT EXISTS TB_PAPEIS (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TB_USUARIOS (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_USUARIO_PAPEIS (
    id_usuario INTEGER NOT NULL,
    id_papeis INTEGER NOT NULL,
    PRIMARY KEY (id_usuario, id_papeis),
    FOREIGN KEY (id_usuario) REFERENCES TB_USUARIOS (id) ON DELETE CASCADE,
    FOREIGN KEY (id_papeis) REFERENCES TB_PAPEIS (id) ON DELETE CASCADE
);